const fs = require('fs');
const path = require('path');

const locales = ['en', 'ta', 'te', 'hi', 'ml', 'kn'];

const content = {
  en: {
    heroTitle: "Transport Information",
    heroSubtitle: "How to Reach Srirangam",
    intro: "Sri Ranganathaswamy Temple is located on Srirangam Island in Tiruchirappalli (Trichy), Tamil Nadu. The temple is well connected by air, rail and road, making it easy for devotees from across India and abroad to visit.",
    busTitle: "Local Bus Stands",
    busChathiram: "From Chathiram Bus Stand",
    busChathiramD: "~5 km",
    busChathiramT: "⏱ 15–20 mins",
    busChathiramL1: "Frequent city buses to Srirangam.",
    busChathiramL2: "Auto-rickshaws readily available.",
    busChathiramL3: "Taxis and app-based cabs offer direct drop.",
    busTrichy: "From Trichy Central Bus Stand",
    busTrichyD: "~10 km",
    busTrichyT: "⏱ 25–35 mins",
    busTrichyL1: "City buses operate regularly.",
    busTrichyL2: "Autos and taxis available outside terminal.",
    busTrichyL3: "Recommended for families travelling with luggage.",
    busPanjapur: "From Panjapur Integrated Terminus",
    busPanjapurD: "~15–18 km",
    busPanjapurT: "⏱ 30–45 mins",
    busPanjapurL1: "Direct or connecting buses.",
    busPanjapurL2: "Allow extra time during peak traffic.",
    trainTitle: "Railway Stations",
    trainSrirangam: "Srirangam Railway Station",
    trainSrirangamD: "~1.5 km from the temple. Easily accessible by walk, auto or taxi.",
    trainTrichy: "Tiruchirappalli Junction",
    trainTrichyD: "~10 km from the temple. City buses, autos and taxis available outside.",
    airTitle: "By Air",
    airD: "~15 km to Airport",
    airT: "⏱ 30–40 mins travel",
    airDesc: "Trichy International Airport has domestic connectivity to Chennai, Bengaluru, Hyderabad, Mumbai, Delhi and Kochi, along with international flights to Singapore, Kuala Lumpur, Colombo and Gulf destinations.",
    airL1: "24×7 prepaid taxis & App-based cabs.",
    airL2: "Airport buses to city with Srirangam connections.",
    trainTravelTitle: "Train Travel from Major Cities",
    thCity: "City",
    thDist: "Distance",
    thTime: "Time",
    roadTravelTitle: "By Road (Driving)",
    parkingTitle: "Parking Information",
    parkingDesc: "Dedicated parking is available around the temple. During weekends and major festivals (like Vaikunta Ekadasi), arrive early as parking fills quickly.",
    tipsTitle: "Travel Tips",
    tip1: "Arrive at least 30 minutes before the queue closing time.",
    tip2: "Expect additional traffic during festivals.",
    tip3: "If your train stops at Srirangam Station, alight there for the shortest transfer.",
    tip4: "Carry drinking water and small cash for local transport.",
    tip5: "Early morning visits are recommended during summer.",
    tip6: "We recommend RedTaxi as a reliable Cab service. Affordable and reliable. Phone Number 0431 456 7890 or you can download Redtaxi from Playstore or Appstore.",
    tip7: "Annadhanam (Free Food/ Meals) Available from 8 am to 9 PM. Waiting time is approx 0-30 minutes."
  },
  ta: {
    heroTitle: "போக்குவரத்து தகவல்",
    heroSubtitle: "ஸ்ரீரங்கத்தை எப்படி அடைவது",
    intro: "ஸ்ரீ ரங்கநாதசுவாமி கோவில் தமிழ்நாட்டின் திருச்சிராப்பள்ளியில் (திருச்சி) உள்ள ஸ்ரீரங்கம் தீவில் அமைந்துள்ளது. விமானம், ரயில் மற்றும் சாலை மார்க்கமாக நன்கு இணைக்கப்பட்டுள்ளது.",
    busTitle: "உள்ளூர் பேருந்து நிலையங்கள்",
    busChathiram: "சத்திரம் பேருந்து நிலையத்திலிருந்து",
    busChathiramD: "~5 கி.மீ",
    busChathiramT: "⏱ 15–20 நிமிடங்கள்",
    busChathiramL1: "ஸ்ரீரங்கத்திற்கு அடிக்கடி நகரப் பேருந்துகள் உள்ளன.",
    busChathiramL2: "ஆட்டோக்கள் எளிதாகக் கிடைக்கும்.",
    busChathiramL3: "டாக்ஸி மற்றும் ஆப்-அடிப்படையிலான கேப்கள் உள்ளன.",
    busTrichy: "மத்திய பேருந்து நிலையத்திலிருந்து",
    busTrichyD: "~10 கி.மீ",
    busTrichyT: "⏱ 25–35 நிமிடங்கள்",
    busTrichyL1: "நகரப் பேருந்துகள் சீராக இயங்குகின்றன.",
    busTrichyL2: "முனையத்திற்கு வெளியே ஆட்டோ மற்றும் டாக்ஸிகள் கிடைக்கின்றன.",
    busTrichyL3: "சாமான்களுடன் பயணம் செய்யும் குடும்பங்களுக்குப் பரிந்துரைக்கப்படுகிறது.",
    busPanjapur: "பஞ்சப்பூர் ஒருங்கிணைந்த முனையத்திலிருந்து",
    busPanjapurD: "~15–18 கி.மீ",
    busPanjapurT: "⏱ 30–45 நிமிடங்கள்",
    busPanjapurL1: "நேரடி அல்லது இணைப்புப் பேருந்துகள்.",
    busPanjapurL2: "நெரிசல் நேரங்களில் கூடுதல் பயண நேரம் தேவைப்படலாம்.",
    trainTitle: "ரயில் நிலையங்கள்",
    trainSrirangam: "ஸ்ரீரங்கம் ரயில் நிலையம்",
    trainSrirangamD: "கோவிலில் இருந்து ~1.5 கி.மீ. நடந்தோ, ஆட்டோ அல்லது டாக்ஸியிலோ எளிதாக அடையலாம்.",
    trainTrichy: "திருச்சிராப்பள்ளி சந்திப்பு",
    trainTrichyD: "கோவிலில் இருந்து ~10 கி.மீ. நகரப் பேருந்துகள், ஆட்டோக்கள் மற்றும் டாக்ஸிகள் கிடைக்கின்றன.",
    airTitle: "விமானம் மூலம்",
    airD: "விமான நிலையத்திற்கு ~15 கி.மீ",
    airT: "⏱ 30–40 நிமிட பயணம்",
    airDesc: "திருச்சி சர்வதேச விமான நிலையம் முக்கிய உள்நாட்டு மற்றும் வெளிநாட்டு நகரங்களுடன் இணைக்கப்பட்டுள்ளது.",
    airL1: "24×7 ப்ரீபெய்ட் டாக்ஸிகள் & ஆப்-அடிப்படையிலான கேப்கள்.",
    airL2: "ஸ்ரீரங்கம் இணைப்புகளுடன் நகரத்திற்கு விமான நிலையப் பேருந்துகள்.",
    trainTravelTitle: "முக்கிய நகரங்களிலிருந்து ரயில் பயணம்",
    thCity: "நகரம்",
    thDist: "தூரம்",
    thTime: "நேரம்",
    roadTravelTitle: "சாலை மார்க்கமாக (வாகனம் மூலம்)",
    parkingTitle: "வாகன நிறுத்துமிடத் தகவல்",
    parkingDesc: "கோவிலைச் சுற்றி பிரத்யேக வாகன நிறுத்துமிடம் உள்ளது. விடுமுறை மற்றும் திருவிழா நாட்களில் சீக்கிரம் வரவும்.",
    tipsTitle: "பயணக் குறிப்புகள்",
    tip1: "வரிசை மூடும் நேரத்திற்கு குறைந்தது 30 நிமிடங்களுக்கு முன்பு வரவும்.",
    tip2: "திருவிழா காலங்களில் போக்குவரத்து நெரிசலை எதிர்பார்க்கலாம்.",
    tip3: "உங்கள் ரயில் ஸ்ரீரங்கம் நிலையத்தில் நின்றால், விரைவாகச் செல்ல அங்கு இறங்கவும்.",
    tip4: "உள்ளூர் பயணங்களுக்கு குடிநீர் மற்றும் சில்லறை பணம் வைத்திருக்கவும்.",
    tip5: "கோடையில் அதிகாலை தரிசனம் பரிந்துரைக்கப்படுகிறது.",
    tip6: "ரெட்டாக்ஸி (RedTaxi) நம்பகமான சேவையாகப் பரிந்துரைக்கிறோம். எண்: 0431 456 7890.",
    tip7: "அன்னதானம் காலை 8 முதல் இரவு 9 வரை கிடைக்கும். காத்திருப்பு நேரம் 0-30 நிமி."
  },
  te: {
    heroTitle: "రవాణా సమాచారం",
    heroSubtitle: "శ్రీరంగానికి ఎలా చేరుకోవాలి",
    intro: "శ్రీ రంగనాథస్వామి ఆలయం తమిళనాడులోని తిరుచిరాపల్లి (ట్రిచీ) శ్రీరంగం దీవిలో ఉంది. ఈ ఆలయానికి విమాన, రైలు మరియు రోడ్డు మార్గాల ద్వారా మంచి రవాణా సౌకర్యాలు ఉన్నాయి.",
    busTitle: "స్థానిక బస్ స్టాండ్‌లు",
    busChathiram: "ఛత్రం బస్ స్టాండ్ నుండి",
    busChathiramD: "~5 కి.మీ",
    busChathiramT: "⏱ 15–20 నిమిషాలు",
    busChathiramL1: "శ్రీరంగానికి సిటీ బస్సులు తరచుగా ఉంటాయి.",
    busChathiramL2: "ఆటోలు సులభంగా అందుబాటులో ఉంటాయి.",
    busChathiramL3: "ట్యాక్సీలు మరియు క్యాబ్‌లు అందుబాటులో ఉన్నాయి.",
    busTrichy: "సెంట్రల్ బస్ స్టాండ్ నుండి",
    busTrichyD: "~10 కి.మీ",
    busTrichyT: "⏱ 25–35 నిమిషాలు",
    busTrichyL1: "సిటీ బస్సులు క్రమం తప్పకుండా నడుస్తాయి.",
    busTrichyL2: "బయట ఆటోలు మరియు ట్యాక్సీలు అందుబాటులో ఉంటాయి.",
    busTrichyL3: "లగేజీతో ప్రయాణించే కుటుంబాలకు అనుకూలం.",
    busPanjapur: "పంజాపూర్ టెర్మినస్ నుండి",
    busPanjapurD: "~15–18 కి.మీ",
    busPanjapurT: "⏱ 30–45 నిమిషాలు",
    busPanjapurL1: "ప్రత్యక్ష లేదా కనెక్టింగ్ బస్సులు.",
    busPanjapurL2: "రద్దీ సమయాల్లో అదనపు సమయం కేటాయించండి.",
    trainTitle: "రైల్వే స్టేషన్లు",
    trainSrirangam: "శ్రీరంగం రైల్వే స్టేషన్",
    trainSrirangamD: "ఆలయం నుండి ~1.5 కి.మీ. నడక, ఆటో లేదా ట్యాక్సీ ద్వారా సులభంగా చేరుకోవచ్చు.",
    trainTrichy: "తిరుచిరాపల్లి జంక్షన్",
    trainTrichyD: "ఆలయం నుండి ~10 కి.మీ. సిటీ బస్సులు, ఆటోలు మరియు ట్యాక్సీలు అందుబాటులో ఉన్నాయి.",
    airTitle: "విమాన మార్గం",
    airD: "విమానాశ్రయానికి ~15 కి.మీ",
    airT: "⏱ 30–40 నిమిషాల ప్రయాణం",
    airDesc: "ట్రిచీ అంతర్జాతీయ విమానాశ్రయానికి ప్రధాన నగరాలు మరియు అంతర్జాతీయ గమ్యస్థానాలకు కనెక్టివిటీ ఉంది.",
    airL1: "24×7 ప్రీపెయిడ్ ట్యాక్సీలు & క్యాబ్‌లు.",
    airL2: "శ్రీరంగానికి కనెక్టివిటీతో ఎయిర్‌పోర్ట్ బస్సులు.",
    trainTravelTitle: "ప్రధాన నగరాల నుండి రైలు ప్రయాణం",
    thCity: "నగరం",
    thDist: "దూరం",
    thTime: "సమయం",
    roadTravelTitle: "రోడ్డు మార్గం (డ్రైవింగ్)",
    parkingTitle: "పార్కింగ్ సమాచారం",
    parkingDesc: "ఆలయం చుట్టూ పార్కింగ్ సౌకర్యం ఉంది. పండుగ రోజుల్లో పార్కింగ్ త్వరగా నిండిపోతుంది కాబట్టి ముందుగా చేరుకోండి.",
    tipsTitle: "ప్రయాణ చిట్కాలు",
    tip1: "క్యూ ముగింపు సమయానికి కనీసం 30 నిమిషాల ముందు చేరుకోండి.",
    tip2: "పండుగల సమయంలో అదనపు రద్దీ ఉంటుంది.",
    tip3: "మీ రైలు శ్రీరంగం స్టేషన్‌లో ఆగితే, సులభంగా చేరుకోవడానికి అక్కడే దిగండి.",
    tip4: "స్థానిక ప్రయాణాలకు త్రాగునీరు మరియు చిల్లర డబ్బును మీ వద్ద ఉంచుకోండి.",
    tip5: "వేసవిలో ఉదయాన్నే సందర్శన సిఫార్సు చేయబడింది.",
    tip6: "మేము రెడ్‌ట్యాక్సీ (RedTaxi) ని సురక్షితమైన సేవగా సిఫార్సు చేస్తున్నాము. ఫోన్ నంబర్: 0431 456 7890.",
    tip7: "అన్నదానం ఉదయం 8 నుండి రాత్రి 9 వరకు అందుబాటులో ఉంటుంది. నిరీక్షణ సమయం 0-30 నిమిషాలు."
  },
  hi: {
    heroTitle: "परिवहन जानकारी",
    heroSubtitle: "श्रीरंगम कैसे पहुँचें",
    intro: "श्री रंगनाथस्वामी मंदिर तमिलनाडु के तिरुचिरापल्ली (त्रिची) में श्रीरंगम द्वीप पर स्थित है। यह मंदिर वायु, रेल और सड़क मार्ग से अच्छी तरह जुड़ा हुआ है।",
    busTitle: "स्थानीय बस स्टैंड",
    busChathiram: "छत्रम बस स्टैंड से",
    busChathiramD: "~5 किमी",
    busChathiramT: "⏱ 15–20 मिनट",
    busChathiramL1: "श्रीरंगम के लिए लगातार सिटी बसें।",
    busChathiramL2: "ऑटो-रिक्शा आसानी से उपलब्ध हैं।",
    busChathiramL3: "टैक्सी और ऐप-आधारित कैब उपलब्ध हैं।",
    busTrichy: "केंद्रीय बस स्टैंड से",
    busTrichyD: "~10 किमी",
    busTrichyT: "⏱ 25–35 मिनट",
    busTrichyL1: "सिटी बसें नियमित रूप से चलती हैं।",
    busTrichyL2: "टर्मिनल के बाहर ऑटो और टैक्सी उपलब्ध हैं।",
    busTrichyL3: "सामान के साथ यात्रा करने वाले परिवारों के लिए अनुशंसित।",
    busPanjapur: "पंजपुर इंटीग्रेटेड टर्मिनस से",
    busPanjapurD: "~15–18 किमी",
    busPanjapurT: "⏱ 30–45 मिनट",
    busPanjapurL1: "डायरेक्ट या कनेक्टिंग बसें।",
    busPanjapurL2: "भीड़भाड़ वाले समय में अतिरिक्त समय दें।",
    trainTitle: "रेलवे स्टेशन",
    trainSrirangam: "श्रीरंगम रेलवे स्टेशन",
    trainSrirangamD: "मंदिर से ~1.5 किमी। पैदल, ऑटो या टैक्सी द्वारा आसानी से पहुँचा जा सकता है।",
    trainTrichy: "तिरुचिरापल्ली जंक्शन",
    trainTrichyD: "मंदिर से ~10 किमी। सिटी बसें, ऑटो और टैक्सी उपलब्ध हैं।",
    airTitle: "हवाई मार्ग से",
    airD: "हवाई अड्डे से ~15 किमी",
    airT: "⏱ 30–40 मिनट की यात्रा",
    airDesc: "त्रिची अंतरराष्ट्रीय हवाई अड्डे से प्रमुख घरेलू और अंतरराष्ट्रीय उड़ानें उपलब्ध हैं।",
    airL1: "24×7 प्रीपेड टैक्सी और कैब।",
    airL2: "श्रीरंगम कनेक्शन के साथ एयरपोर्ट बसें।",
    trainTravelTitle: "प्रमुख शहरों से ट्रेन यात्रा",
    thCity: "शहर",
    thDist: "दूरी",
    thTime: "समय",
    roadTravelTitle: "सड़क मार्ग से (ड्राइविंग)",
    parkingTitle: "पार्किंग की जानकारी",
    parkingDesc: "मंदिर के चारों ओर समर्पित पार्किंग उपलब्ध है। त्योहारों के दौरान जल्दी पहुँचें।",
    tipsTitle: "यात्रा के लिए सुझाव",
    tip1: "कतार बंद होने के समय से कम से कम 30 मिनट पहले पहुँचें।",
    tip2: "त्योहारों के दौरान अतिरिक्त ट्रैफ़िक की अपेक्षा करें।",
    tip3: "यदि आपकी ट्रेन श्रीरंगम स्टेशन पर रुकती है, तो सबसे कम स्थानांतरण के लिए वहीं उतरें।",
    tip4: "स्थानीय परिवहन के लिए पीने का पानी और छोटी नकदी साथ रखें।",
    tip5: "गर्मियों के दौरान सुबह जल्दी दर्शन करने की सलाह दी जाती है।",
    tip6: "हम रेडटैक्सी (RedTaxi) को एक विश्वसनीय कैब सेवा के रूप में अनुशंसित करते हैं। फोन: 0431 456 7890.",
    tip7: "अन्नदानम सुबह 8 बजे से रात 9 बजे तक उपलब्ध है। प्रतीक्षा का समय 0-30 मिनट है।"
  },
  ml: {
    heroTitle: "ഗതാഗത വിവരങ്ങൾ",
    heroSubtitle: "ശ്രീരംഗത്തിൽ എങ്ങനെ എത്തിച്ചേരാം",
    intro: "തമിഴ്‌നാട്ടിലെ തിരുച്ചിറപ്പള്ളിയിൽ (ട്രിച്ചി) ശ്രീരംഗം ദ്വീപിലാണ് ശ്രീ രംഗനാഥസ്വാമി ക്ഷേത്രം സ്ഥിതിചെയ്യുന്നത്. വായു, റെയിൽ, റോഡ് മാർഗ്ഗങ്ങളിലൂടെ ഇവിടേക്ക് എളുപ്പത്തിൽ എത്തിച്ചേരാം.",
    busTitle: "പ്രാദേശിക ബസ് സ്റ്റാൻഡുകൾ",
    busChathiram: "ചത്രം ബസ് സ്റ്റാൻഡിൽ നിന്ന്",
    busChathiramD: "~5 കി.മീ",
    busChathiramT: "⏱ 15–20 മിനിറ്റ്",
    busChathiramL1: "ശ്രീരംഗത്തേക്ക് ഇടവിട്ട് സിറ്റി ബസുകളുണ്ട്.",
    busChathiramL2: "ഓട്ടോ റിക്ഷകൾ എളുപ്പത്തിൽ ലഭിക്കും.",
    busChathiramL3: "ടാക്സികളും ആപ്പ് അധിഷ്ഠിത ക്യാബുകളും ലഭ്യമാണ്.",
    busTrichy: "സെൻട്രൽ ബസ് സ്റ്റാൻഡിൽ നിന്ന്",
    busTrichyD: "~10 കി.മീ",
    busTrichyT: "⏱ 25–35 മിനിറ്റ്",
    busTrichyL1: "സിറ്റി ബസുകൾ കൃത്യമായി സർവീസ് നടത്തുന്നു.",
    busTrichyL2: "ബസ് സ്റ്റാൻഡിന് പുറത്ത് ഓട്ടോകളും ടാക്സികളും ലഭ്യമാണ്.",
    busTrichyL3: "ലഗേജുമായി യാത്ര ചെയ്യുന്ന കുടുംബങ്ങൾക്ക് അനുയോജ്യം.",
    busPanjapur: "പഞ്ചപ്പൂർ ടെർമിനസിൽ നിന്ന്",
    busPanjapurD: "~15–18 കി.മീ",
    busPanjapurT: "⏱ 30–45 മിനിറ്റ്",
    busPanjapurL1: "നേരിട്ടുള്ളതോ കണക്റ്റിംഗ് ബസുകളോ.",
    busPanjapurL2: "തിരക്കുള്ള സമയങ്ങളിൽ അധിക സമയം പ്രതീക്ഷിക്കുക.",
    trainTitle: "റെയിൽവേ സ്റ്റേഷനുകൾ",
    trainSrirangam: "ശ്രീരംഗം റെയിൽവേ സ്റ്റേഷൻ",
    trainSrirangamD: "ക്ഷേത്രത്തിൽ നിന്ന് ~1.5 കി.മീ. നടന്നും ഓട്ടോയിലോ ടാക്സിയിലോ എളുപ്പത്തിൽ എത്തിച്ചേരാം.",
    trainTrichy: "തിരുച്ചിറപ്പള്ളി ജംഗ്ഷൻ",
    trainTrichyD: "ക്ഷേത്രത്തിൽ നിന്ന് ~10 കി.മീ. സിറ്റി ബസുകളും ഓട്ടോകളും ടാക്സികളും ലഭ്യമാണ്.",
    airTitle: "വിമാന മാർഗ്ഗം",
    airD: "എയർപോർട്ടിലേക്ക് ~15 കി.മീ",
    airT: "⏱ 30–40 മിനിറ്റ് യാത്ര",
    airDesc: "ട്രിച്ചി അന്താരാഷ്ട്ര വിമാനത്താവളത്തിൽ നിന്ന് പ്രധാന നഗരങ്ങളിലേക്കും വിദേശത്തേക്കും വിമാന സൗകര്യമുണ്ട്.",
    airL1: "24×7 പ്രീപെയ്ഡ് ടാക്സികളും ക്യാബുകളും.",
    airL2: "ശ്രീരംഗം കണക്ഷനുകളുള്ള എയർപോർട്ട് ബസുകൾ.",
    trainTravelTitle: "പ്രധാന നഗരങ്ങളിൽ നിന്നുള്ള ട്രെയിൻ യാത്ര",
    thCity: "നഗരം",
    thDist: "ദൂരം",
    thTime: "സമയം",
    roadTravelTitle: "റോഡ് മാർഗ്ഗം",
    parkingTitle: "പാർക്കിംഗ് വിവരങ്ങൾ",
    parkingDesc: "ക്ഷേത്രത്തിന് ചുറ്റും പാർക്കിംഗ് ലഭ്യമാണ്. ഉത്സവ സമയങ്ങളിൽ പാർക്കിംഗ് വേഗത്തിൽ നിറയുന്നതിനാൽ നേരത്തെ എത്തുക.",
    tipsTitle: "യാത്രാ നുറുങ്ങുകൾ",
    tip1: "ക്യൂ അവസാനിക്കുന്നതിന് 30 മിനിറ്റ് മുമ്പെങ്കിലും എത്തിച്ചേരുക.",
    tip2: "ഉത്സവ സമയങ്ങളിൽ കൂടുതൽ ട്രാഫിക് പ്രതീക്ഷിക്കുക.",
    tip3: "നിങ്ങളുടെ ട്രെയിനിന് ശ്രീരംഗം സ്റ്റേഷനിൽ സ്റ്റോപ്പുണ്ടെങ്കിൽ അവിടെ ഇറങ്ങുക.",
    tip4: "പ്രാദേശിക യാത്രാ ആവശ്യങ്ങൾക്ക് കുടിവെള്ളവും ചില്ലറയും കരുതുക.",
    tip5: "വേനൽക്കാലത്ത് അതിരാവിലെ ക്ഷേത്രദർശനം നടത്തുന്നത് നല്ലതാണ്.",
    tip6: "വിശ്വസനീയമായ ഒരു ക്യാബ് സേവനമായി റെഡ് ടാക്സി (RedTaxi) ശുപാർശ ചെയ്യുന്നു. ഫോൺ: 0431 456 7890.",
    tip7: "അന്നദാനം രാവിലെ 8 മുതൽ രാത്രി 9 വരെ ലഭ്യമാണ്. കാത്തിരിപ്പ് സമയം ഏകദേശം 0-30 മിനിറ്റ്."
  },
  kn: {
    heroTitle: "ಸಾರಿಗೆ ಮಾಹಿತಿ",
    heroSubtitle: "ಶ್ರೀರಂಗಂ ತಲುಪುವುದು ಹೇಗೆ",
    intro: "ಶ್ರೀ ರಂಗನಾಥಸ್ವಾಮಿ ದೇವಾಲಯವು ತಮಿಳುನಾಡಿನ ತಿರುಚಿರಾಪಳ್ಳಿ (ಟ್ರಿಚಿ) ಯ ಶ್ರೀರಂಗಂ ದ್ವೀಪದಲ್ಲಿದೆ. ಈ ದೇವಾಲಯವು ವಿಮಾನ, ರೈಲು ಮತ್ತು ರಸ್ತೆ ಮಾರ್ಗಗಳ ಮೂಲಕ ಉತ್ತಮ ಸಂಪರ್ಕ ಹೊಂದಿದೆ.",
    busTitle: "ಸ್ಥಳೀಯ ಬಸ್ ನಿಲ್ದಾಣಗಳು",
    busChathiram: "ಛತ್ರಂ ಬಸ್ ನಿಲ್ದಾಣದಿಂದ",
    busChathiramD: "~5 ಕಿ.ಮೀ",
    busChathiramT: "⏱ 15–20 ನಿಮಿಷಗಳು",
    busChathiramL1: "ಶ್ರೀರಂಗಂಗೆ ಆಗಾಗ್ಗೆ ಸಿಟಿ ಬಸ್‌ಗಳಿವೆ.",
    busChathiramL2: "ಆಟೋಗಳು ಸುಲಭವಾಗಿ ಲಭ್ಯವಿದೆ.",
    busChathiramL3: "ಟ್ಯಾಕ್ಸಿಗಳು ಮತ್ತು ಕ್ಯಾಬ್‌ಗಳು ಲಭ್ಯವಿದೆ.",
    busTrichy: "ಕೇಂದ್ರ ಬಸ್ ನಿಲ್ದಾಣದಿಂದ",
    busTrichyD: "~10 ಕಿ.ಮೀ",
    busTrichyT: "⏱ 25–35 ನಿಮಿಷಗಳು",
    busTrichyL1: "ಸಿಟಿ ಬಸ್‌ಗಳು ನಿಯಮಿತವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ.",
    busTrichyL2: "ನಿಲ್ದಾಣದ ಹೊರಗೆ ಆಟೋ ಮತ್ತು ಟ್ಯಾಕ್ಸಿ ಲಭ್ಯವಿದೆ.",
    busTrichyL3: "ಲಗೇಜ್ ಹೊಂದಿರುವ ಕುಟುಂಬಗಳಿಗೆ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    busPanjapur: "ಪಂಜಪುರ್ ಟರ್ಮಿನಸ್‌ನಿಂದ",
    busPanjapurD: "~15–18 ಕಿ.ಮೀ",
    busPanjapurT: "⏱ 30–45 ನಿಮಿಷಗಳು",
    busPanjapurL1: "ನೇರ ಅಥವಾ ಕನೆಕ್ಟಿಂಗ್ ಬಸ್‌ಗಳು.",
    busPanjapurL2: "ಟ್ರಾಫಿಕ್ ಸಮಯದಲ್ಲಿ ಹೆಚ್ಚುವರಿ ಸಮಯ ಬೇಕಾಗಬಹುದು.",
    trainTitle: "ರೈಲು ನಿಲ್ದಾಣಗಳು",
    trainSrirangam: "ಶ್ರೀರಂಗಂ ರೈಲು ನಿಲ್ದಾಣ",
    trainSrirangamD: "ದೇವಾಲಯದಿಂದ ~1.5 ಕಿ.ಮೀ. ನಡೆದು, ಆಟೋ ಅಥವಾ ಟ್ಯಾಕ್ಸಿ ಮೂಲಕ ಸುಲಭವಾಗಿ ತಲುಪಬಹುದು.",
    trainTrichy: "ತಿರುಚಿರಾಪಳ್ಳಿ ಜಂಕ್ಷನ್",
    trainTrichyD: "ದೇವಾಲಯದಿಂದ ~10 ಕಿ.ಮೀ. ಸಿಟಿ ಬಸ್‌ಗಳು, ಆಟೋಗಳು ಮತ್ತು ಟ್ಯಾಕ್ಸಿಗಳು ಲಭ್ಯವಿದೆ.",
    airTitle: "ವಿಮಾನ ಮಾರ್ಗ",
    airD: "ವಿಮಾನ ನಿಲ್ದಾಣಕ್ಕೆ ~15 ಕಿ.ಮೀ",
    airT: "⏱ 30–40 ನಿಮಿಷಗಳ ಪ್ರಯಾಣ",
    airDesc: "ಟ್ರಿಚಿ ಅಂತರಾಷ್ಟ್ರೀಯ ವಿಮಾನ ನಿಲ್ದಾಣವು ಪ್ರಮುಖ ದೇಶೀಯ ಮತ್ತು ಅಂತರಾಷ್ಟ್ರೀಯ ಸಂಪರ್ಕವನ್ನು ಹೊಂದಿದೆ.",
    airL1: "24×7 ಪ್ರಿಪೇಯ್ಡ್ ಟ್ಯಾಕ್ಸಿಗಳು ಮತ್ತು ಕ್ಯಾಬ್‌ಗಳು.",
    airL2: "ಶ್ರೀರಂಗಂ ಸಂಪರ್ಕದೊಂದಿಗೆ ವಿಮಾನ ನಿಲ್ದಾಣದ ಬಸ್‌ಗಳು.",
    trainTravelTitle: "ಪ್ರಮುಖ ನಗರಗಳಿಂದ ರೈಲು ಪ್ರಯಾಣ",
    thCity: "ನಗರ",
    thDist: "ದೂರ",
    thTime: "ಸಮಯ",
    roadTravelTitle: "ರಸ್ತೆ ಮಾರ್ಗ (ಚಾಲನೆ)",
    parkingTitle: "ಪಾರ್ಕಿಂಗ್ ಮಾಹಿತಿ",
    parkingDesc: "ದೇವಾಲಯದ ಸುತ್ತಲೂ ಪಾರ್ಕಿಂಗ್ ಲಭ್ಯವಿದೆ. ಹಬ್ಬದ ದಿನಗಳಲ್ಲಿ ಪಾರ್ಕಿಂಗ್ ಬೇಗನೆ ಭರ್ತಿಯಾಗುವುದರಿಂದ ಬೇಗನೆ ಬನ್ನಿ.",
    tipsTitle: "ಪ್ರಯಾಣ ಸಲಹೆಗಳು",
    tip1: "ಕ್ಯೂ ಮುಚ್ಚುವ ಸಮಯಕ್ಕಿಂತ ಕನಿಷ್ಠ 30 ನಿಮಿಷಗಳ ಮೊದಲು ತಲುಪಿ.",
    tip2: "ಹಬ್ಬಗಳ ಸಮಯದಲ್ಲಿ ಹೆಚ್ಚುವರಿ ಟ್ರಾಫಿಕ್ ನಿರೀಕ್ಷಿಸಿ.",
    tip3: "ನಿಮ್ಮ ರೈಲು ಶ್ರೀರಂಗಂ ನಿಲ್ದಾಣದಲ್ಲಿ ನಿಲ್ಲುವುದಾದರೆ, ಸುಲಭವಾಗಿ ತಲುಪಲು ಅಲ್ಲಿಯೇ ಇಳಿಯಿರಿ.",
    tip4: "ಸ್ಥಳೀಯ ಪ್ರಯಾಣಕ್ಕಾಗಿ ಕುಡಿಯುವ ನೀರು ಮತ್ತು ಚಿಲ್ಲರೆ ಹಣವನ್ನು ಹೊಂದಿರಿ.",
    tip5: "ಬೇಸಿಗೆಯಲ್ಲಿ ಮುಂಜಾನೆಯ ಭೇಟಿಯನ್ನು ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ.",
    tip6: "ನಾವು ರೆಡ್ ಟ್ಯಾಕ್ಸಿಯನ್ನು (RedTaxi) ವಿಶ್ವಾಸಾರ್ಹ ಕ್ಯಾಬ್ ಸೇವೆಯಾಗಿ ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ. ಫೋನ್: 0431 456 7890.",
    tip7: "ಅನ್ನದಾನವು ಬೆಳಿಗ್ಗೆ 8 ರಿಂದ ರಾತ್ರಿ 9 ರವರೆಗೆ ಲಭ್ಯವಿದೆ. ಕಾಯುವ ಸಮಯ 0-30 ನಿಮಿಷಗಳು."
  }
};

locales.forEach(loc => {
  const p = path.join(__dirname, 'src/dictionaries', `${loc}.json`);
  let data = {};
  if (fs.existsSync(p)) {
    data = JSON.parse(fs.readFileSync(p, 'utf8'));
  }
  
  data.transport = content[loc];
  
  fs.writeFileSync(p, JSON.stringify(data, null, 2));
});

console.log("Transport translations added for all locales.");
